/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Trip */
        post: operations["submit_trip_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result */
        get: operations["get_run_result_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Budget */
        Budget: {
            /**
             * Currency
             * @default AUD
             */
            currency: string;
            /** Total */
            total?: number | null;
            /** Per Day */
            per_day?: number | null;
        };
        /**
         * Check
         * @description The Auditor's judgement on one claim. Written by verification, never by research.
         */
        Check: {
            verdict: components["schemas"]["Verdict"];
            /** Confidence */
            confidence: number;
            /**
             * Reason
             * @description One sentence, grounded in the cited evidence.
             */
            reason: string;
            /** Supporting Evidence Ids */
            supporting_evidence_ids?: string[];
            /** Conflicting Evidence Ids */
            conflicting_evidence_ids?: string[];
            /** Model */
            model?: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
        };
        /**
         * Claim
         * @description One falsifiable assertion, with its provenance and — after verification — its verdict.
         */
        Claim: {
            /** Id */
            id?: string;
            /**
             * Subject
             * @description What the claim is about, e.g. 'Museo del Prado'.
             */
            subject: string;
            /**
             * Text
             * @description A single assertion. Split anything compound.
             */
            text: string;
            /** @default other */
            kind: components["schemas"]["ClaimKind"];
            /** Evidence Ids */
            evidence_ids?: string[];
            check?: components["schemas"]["Check"] | null;
        };
        /**
         * ClaimKind
         * @description Determines how volatile a claim is, and therefore how fast its evidence rots.
         * @enum {string}
         */
        ClaimKind: "hours" | "price" | "availability" | "transit" | "location" | "description" | "safety" | "other";
        /** ContentPiece */
        ContentPiece: {
            /**
             * Kind
             * @description itinerary_doc, article, thread, captions, checklist
             */
            kind: string;
            /** Title */
            title?: string | null;
            /** Body */
            body: string;
            /** Word Count */
            word_count?: number | null;
            /**
             * Claim Ids
             * @description Verified claims this piece states as fact, when it makes one.
             */
            claim_ids?: string[];
        };
        /**
         * ContentSet
         * @description Output of the Chronicler: the human-facing artifacts.
         */
        ContentSet: {
            /** Itinerary Id */
            itinerary_id: string;
            /** Pieces */
            pieces?: components["schemas"]["ContentPiece"][];
            /**
             * Caveats
             * @description Drafted pieces that were dropped, and why — never silently discarded.
             */
            caveats?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Evidence
         * @description A retrieved passage, kept verbatim so verification has something to check against.
         */
        Evidence: {
            /** Id */
            id?: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Title */
            title?: string | null;
            /**
             * Snippet
             * @description Verbatim excerpt. Never a model paraphrase.
             */
            snippet: string;
            /** @default unknown */
            source_kind: components["schemas"]["SourceKind"];
            /**
             * Published At
             * @description Publication or last-updated date, when the page states one.
             */
            published_at?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /**
             * Query
             * @description Search query that surfaced this.
             */
            query?: string | null;
        };
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Itinerary
         * @description Output of the Navigator. Every item is traceable to usable claims.
         */
        Itinerary: {
            /** Id */
            id?: string;
            /** Brief Id */
            brief_id: string;
            /** Destination */
            destination: string;
            /** Days */
            days?: components["schemas"]["ItineraryDay"][];
            /** Places */
            places?: components["schemas"]["Place"][];
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * Caveats
             * @description Contradicted or stale facts the traveller should re-check on the day.
             */
            caveats?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ItineraryDay */
        ItineraryDay: {
            /** Day */
            day: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Theme */
            theme?: string | null;
            /** Items */
            items?: components["schemas"]["ItineraryItem"][];
        };
        /** ItineraryItem */
        ItineraryItem: {
            /** Id */
            id?: string;
            /** Day */
            day: number;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Title */
            title: string;
            /** Place Id */
            place_id?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Claim Ids
             * @description Every fact this item rests on.
             */
            claim_ids?: string[];
            transfer_in?: components["schemas"]["Transfer"] | null;
            /**
             * Booking Required
             * @default false
             */
            booking_required: boolean;
            /** Estimated Cost */
            estimated_cost?: number | null;
        };
        /**
         * ModelCall
         * @description One recorded LLM invocation. The audit trail behind every produced fact.
         */
        ModelCall: {
            /** Id */
            id?: string;
            stage: components["schemas"]["Stage"];
            /** Model */
            model: string;
            /** Prompt Hash */
            prompt_hash: string;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Called At
             * Format: date-time
             */
            called_at?: string;
        };
        /**
         * Pace
         * @enum {string}
         */
        Pace: "relaxed" | "balanced" | "packed";
        /**
         * Party
         * @description Who is travelling. Shapes both what is proposed and what is ruled out.
         */
        Party: {
            /**
             * Adults
             * @default 1
             */
            adults: number;
            /**
             * Children
             * @default 0
             */
            children: number;
            /** Child Ages */
            child_ages?: number[];
            /** Mobility Notes */
            mobility_notes?: string | null;
        };
        /** Place */
        Place: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** @default other */
            kind: components["schemas"]["PlaceKind"];
            /** Address */
            address?: string | null;
            point?: components["schemas"]["GeoPoint"] | null;
            /**
             * Summary
             * @description Why this belongs in this trip, in one or two sentences.
             */
            summary?: string | null;
            /** Claim Ids */
            claim_ids?: string[];
            /** Typical Duration Minutes */
            typical_duration_minutes?: number | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * PlaceKind
         * @enum {string}
         */
        PlaceKind: "sight" | "museum" | "outdoors" | "food" | "nightlife" | "shopping" | "lodging" | "transport" | "event" | "other";
        /**
         * ResearchBundle
         * @description Output of the Explorer. Claims here are unverified by construction.
         */
        ResearchBundle: {
            /** Brief Id */
            brief_id: string;
            /** Places */
            places?: components["schemas"]["Place"][];
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Queries Run */
            queries_run?: string[];
            /**
             * Gaps
             * @description What the Explorer looked for and could not find.
             */
            gaps?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Run
         * @description One end-to-end execution, with each stage boundary retained for replay.
         */
        Run: {
            /** Id */
            id?: string;
            brief: components["schemas"]["TripBrief"];
            /** @default pending */
            status: components["schemas"]["RunStatus"];
            /** Stages */
            stages?: components["schemas"]["StageRun"][];
            research?: components["schemas"]["ResearchBundle"] | null;
            verified?: components["schemas"]["VerifiedBundle"] | null;
            itinerary?: components["schemas"]["Itinerary"] | null;
            content?: components["schemas"]["ContentSet"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** RunCounts */
        RunCounts: {
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /**
             * Claims
             * @default 0
             */
            claims: number;
            /**
             * Verified Claims
             * @default 0
             */
            verified_claims: number;
            /**
             * Itinerary Items
             * @default 0
             */
            itinerary_items: number;
            /**
             * Content Pieces
             * @default 0
             */
            content_pieces: number;
        };
        /** RunResultView */
        RunResultView: {
            /** Id */
            id: string;
            status: components["schemas"]["RunStatus"];
            /** Error */
            error?: string | null;
            run?: components["schemas"]["Run"] | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * RunSummary
         * @description Small polling payload derived from Hermes' live Run without stage artifacts.
         */
        RunSummary: {
            /** Id */
            id: string;
            status: components["schemas"]["RunStatus"];
            /** Error */
            error?: string | null;
            brief: components["schemas"]["TripBriefSummary"];
            current_stage?: components["schemas"]["Stage"] | null;
            /** Stages */
            stages: components["schemas"]["StageProgress"][];
            counts: components["schemas"]["RunCounts"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "official" | "government" | "encyclopedia" | "guide" | "review" | "map" | "unknown";
        /**
         * Stage
         * @enum {string}
         */
        Stage: "research" | "verify" | "plan" | "write";
        /** StageProgress */
        StageProgress: {
            stage: components["schemas"]["Stage"];
            status?: components["schemas"]["RunStatus"] | null;
            /** Attempt */
            attempt?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** StageRun */
        StageRun: {
            stage: components["schemas"]["Stage"];
            /** @default pending */
            status: components["schemas"]["RunStatus"];
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /** Calls */
            calls?: components["schemas"]["ModelCall"][];
            /**
             * Queries
             * @default 0
             */
            queries: number;
            /**
             * Fetches
             * @default 0
             */
            fetches: number;
            /**
             * Tokens
             * @default 0
             */
            tokens: number;
        };
        /**
         * Transfer
         * @description How the traveller gets from the previous item to this one.
         */
        Transfer: {
            /**
             * Mode
             * @description walk, metro, bus, train, ferry, taxi, drive
             */
            mode: string;
            /** Minutes */
            minutes: number;
            /**
             * Meters
             * @description Set when Navigator grounded this transfer against a real route; unset when no coordinates were available to look one up.
             */
            meters?: number | null;
            /** Detail */
            detail?: string | null;
            /** Claim Ids */
            claim_ids?: string[];
        };
        /**
         * TripBrief
         * @description The pipeline's input. Everything downstream is traceable to one of these.
         */
        TripBrief: {
            /** Id */
            id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            party?: components["schemas"]["Party"];
            budget?: components["schemas"]["Budget"];
            /** Interests */
            interests?: string[];
            /** Must See */
            must_see?: string[];
            /** Avoid */
            avoid?: string[];
            /** Dietary */
            dietary?: string[];
            /** @default balanced */
            pace: components["schemas"]["Pace"];
            /**
             * Base Location
             * @description Hotel or neighbourhood days start and end from.
             */
            base_location?: string | null;
            /**
             * Language
             * @description Language of the produced content.
             * @default en
             */
            language: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TripBriefCreate
         * @description Caller-owned fields for a trip; identity and timestamps stay server-owned.
         */
        TripBriefCreate: {
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            party?: components["schemas"]["Party"];
            budget?: components["schemas"]["Budget"];
            /** Interests */
            interests?: string[];
            /** Must See */
            must_see?: string[];
            /** Avoid */
            avoid?: string[];
            /** Dietary */
            dietary?: string[];
            /** @default balanced */
            pace: components["schemas"]["Pace"];
            /** Base Location */
            base_location?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Notes */
            notes?: string | null;
        };
        /** TripBriefSummary */
        TripBriefSummary: {
            /** Destination */
            destination: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "supported" | "partial" | "contradicted" | "unsupported" | "no_evidence" | "stale";
        /**
         * VerifiedBundle
         * @description Output of the Auditor: the same bundle, with every claim carrying a check.
         */
        VerifiedBundle: {
            /** Brief Id */
            brief_id: string;
            /** Places */
            places?: components["schemas"]["Place"][];
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Queries Run */
            queries_run?: string[];
            /**
             * Gaps
             * @description What the Explorer looked for and could not find.
             */
            gaps?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_trip_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripBriefCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
